const rawData = [
    {
        "id": "U1092",
        "name": "預約未來的我：社會趨勢中的自我探索",
        "teacher": "王冠生",
        "dim": "向度二",
        "time": "每週二5~6",
        "room": "社203",
        "credit": "2",
        "limit": 50,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "請優先排在社科203(翻轉教室)。"
    },
    {
        "id": "U2020",
        "name": "時代與歷史",
        "teacher": "何淑宜",
        "dim": "向度六",
        "time": "每週四7~8",
        "room": "",
        "credit": "2",
        "limit": 40,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "請排文學院2樓的教室。謝謝。此為大學入門課程，志願選課階段限1、2年級選讀，加退選階段開放所有年級選讀。總人數限制為50人。歷史系學生選讀，不列入其通識畢業學分數。"
    },
    {
        "id": "U2058",
        "name": "全球化與多元文化",
        "teacher": "張喬婷",
        "dim": "向度四",
        "time": "每週五7~8",
        "room": "社113",
        "credit": "2",
        "limit": 40,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "此為大學入門課程，志願選課階段限1、2年級選讀，加退選階段開放所有年級選讀。總人數限制為60人。"
    },
    {
        "id": "U2071",
        "name": "觀光概論",
        "teacher": "洪維勵",
        "dim": "向度四",
        "time": "每週三7~8",
        "room": "商1F15",
        "credit": "2",
        "limit": 30,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "休運系學生選讀，不列入其通識畢業學分數。此為大學入門課程，志願選課階段限1、2年級選讀30人，加退選階段開放所有年級選讀。總限修人數40人。"
    },
    {
        "id": "U2135",
        "name": "政治與現代社會",
        "teacher": "張朝琴",
        "dim": "向度三",
        "time": "每週五1~2",
        "room": "社102",
        "credit": "2",
        "limit": 40,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "行政系、經濟系學生修習不列入通識畢業學分。此為大學入門課程，志願選課階段限1、2年級選讀，加退選階段開放所有年級選讀。總人數限制為60人。"
    },
    {
        "id": "U2175",
        "name": "全球化與多元文化",
        "teacher": "曾秀珍",
        "dim": "向度四",
        "time": "每週一3~4",
        "room": "社113",
        "credit": "2",
        "limit": 40,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": "此為大學入門課程，志願選課階段限1、2年級選讀，加退選階段開放所有年級選讀。總人數限制為50人。 請安排社科112 教室。"
    },
    {
        "id": "U2179",
        "name": "情緒管理與壓力調適",
        "teacher": "吳國淳",
        "dim": "向度二",
        "time": "每週二5~6",
        "room": "法2F13",
        "credit": "2",
        "limit": 40,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": "此為大學入門課程，志願選課階段限1、2年級選讀，加退選階段開放所有年級選讀。總人數限制為45人。"
    },
    {
        "id": "U2182",
        "name": "情緒管理與壓力調適",
        "teacher": "吳國淳",
        "dim": "向度二",
        "time": "每週一5~6",
        "room": "法2F13",
        "credit": "2",
        "limit": 40,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": "此為大學入門課程，志願選課階段限1、2年級選讀，加退選階段開放所有年級選讀。總人數限制為45人。"
    },
    {
        "id": "U2204",
        "name": "文學詮釋與生命哲學",
        "teacher": "吳惠玲",
        "dim": "向度一",
        "time": "每週二3~4",
        "room": "文1F11",
        "credit": "2",
        "limit": 70,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "1.請安排於人文1F11教室 2.原「文學與人生」更名，請勿重複修讀 3.此為大學入門課程，志願選課階段限一、二年級70人選修，加退選階段開放所有年級選修，總限修人數90人 4.人工加簽限收3名 5.中文系學生選讀，不列入通識畢業學分數"
    },
    {
        "id": "U2276",
        "name": "生物多樣性",
        "teacher": "陳湘繁",
        "dim": "向度五",
        "time": "每週一3~4",
        "room": "公1F14",
        "credit": "2",
        "limit": 50,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "請安排教室\"公114\"。此為大學入門課程，志願選課階段限1、2年級選讀，加退選階段開放所有年級選讀。總人數限制60人。"
    },
    {
        "id": "U4007",
        "name": "二十世紀德國史",
        "teacher": "伍碧雯",
        "dim": "向度六",
        "time": "每週四3~4",
        "room": "",
        "credit": "2",
        "limit": 40,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "教室請儘量排社科院2F02教室。歷史系學生選讀,不列入其通識畢業學分數。 伍碧雯老師通識課程完全由學校電腦決定學生名單，不接受人工加簽。請同學不要寫e-mail詢問老師。"
    },
    {
        "id": "U4010",
        "name": "文化創意產業",
        "teacher": "雷碧秀",
        "dim": "向度四",
        "time": "每週一5~6",
        "room": "社114_互動",
        "credit": "2",
        "limit": 40,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": ""
    },
    {
        "id": "U4016",
        "name": "當代華文戲劇",
        "teacher": "趙雪君",
        "dim": "向度一",
        "time": "每週二7~8",
        "room": "文2F10",
        "credit": "2",
        "limit": 50,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "中文系學生修習不列入通識畢業學分"
    },
    {
        "id": "U4019",
        "name": "看影集學賽局",
        "teacher": "邱敬淵",
        "dim": "向度四",
        "time": "每週四3~4",
        "room": "",
        "credit": "2",
        "limit": 40,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "經濟學系學生選讀，不列入其通識畢業學分數。 敬請安排社101教室。"
    },
    {
        "id": "U4020",
        "name": "中華民國憲法",
        "teacher": "詹靜芬",
        "dim": "向度三",
        "time": "每週三3~4",
        "room": "公1F27",
        "credit": "2",
        "limit": 128,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "行政系、法律系學生修習不列入通識畢業學分。"
    },
    {
        "id": "U4027",
        "name": "倫理學與當代議題",
        "teacher": "陳莉莉",
        "dim": "向度二",
        "time": "每週五3~4",
        "room": "公1F01",
        "credit": "2",
        "limit": 60,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "原「倫理學」更名。行政系學生選讀，不列入其通識畢業學分數。"
    },
    {
        "id": "U4028",
        "name": "網路生活應用",
        "teacher": "溫演福",
        "dim": "向度五",
        "time": "每週二3~4",
        "room": "法2F03",
        "credit": "2",
        "limit": 80,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": ""
    },
    {
        "id": "U4029",
        "name": "建築環境之美",
        "teacher": "張喬婷",
        "dim": "向度五",
        "time": "每週五5~6",
        "room": "社113",
        "credit": "2",
        "limit": 60,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": ""
    },
    {
        "id": "U4031",
        "name": "宮廷名物賞析",
        "teacher": "林士鉉",
        "dim": "向度六",
        "time": "每週四3~4",
        "room": "",
        "credit": "2",
        "limit": 50,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": ""
    },
    {
        "id": "U4032",
        "name": "運算思維與程式設計",
        "teacher": "許銘芳",
        "dim": "向度五",
        "time": "每週五3~4",
        "room": "資1F-14",
        "credit": "2",
        "limit": 50,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": "資工系、企管系學生選讀，不列入其通識畢業學分數。"
    },
    {
        "id": "U4036",
        "name": "海山地區觀光美語",
        "teacher": "藍蕾",
        "dim": "向度一",
        "time": "每週四5~6",
        "room": "文4F05_L",
        "credit": "2",
        "limit": 30,
        "enrolled": 0,
        "can_add": "否",
        "lang": "英語 English",
        "note": "英語授課。建議英文程度為全民英檢中級(含)以上者選修。應外系學生修習不列入通識畢業學分。 麻煩安排人文大樓4F05教室"
    },
    {
        "id": "U4040",
        "name": "運算思維與程式設計",
        "teacher": "溫演福",
        "dim": "向度五",
        "time": "每週四3~4",
        "room": "",
        "credit": "2",
        "limit": 60,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": "資工系、企管系學生選讀，不列入其通識畢業學分數。"
    },
    {
        "id": "U4048",
        "name": "租稅與生活",
        "teacher": "曾光文",
        "dim": "向度四",
        "time": "每週二7~8",
        "room": "公1F30",
        "credit": "2",
        "limit": 97,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "經濟系、財政系學生選讀，不列入其通識畢業學分數。"
    },
    {
        "id": "U4054",
        "name": "SAS EG巨量數據分析概論",
        "teacher": "陳介然",
        "dim": "向度五",
        "time": "每週五1~2",
        "room": "法1F04",
        "credit": "2",
        "limit": 60,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "1.統計學系學生選讀，不列入通識教育畢業學分數。2.須自備筆記型電腦，並至校園授權軟體網，安裝SAS 9.4版(內有SAS EG)統計軟體(Mac不支援)。"
    },
    {
        "id": "U4057",
        "name": "公民暨道德教育",
        "teacher": "黃薏文",
        "dim": "向度二",
        "time": "每週一5~6",
        "room": "社203",
        "credit": "2",
        "limit": 50,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "請安排社203"
    },
    {
        "id": "U4058",
        "name": "客家文化創意的發展",
        "teacher": "陳淑惠",
        "dim": "向度四",
        "time": "每週五5~8",
        "room": "文6F06",
        "credit": "2",
        "limit": 23,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": "請安排文606教室。本課程為密集課程。實際上課時間請詳閱課程大綱。成果展時間另訂。"
    },
    {
        "id": "U4063",
        "name": "職場與法律",
        "teacher": "陳介然",
        "dim": "向度三",
        "time": "每週五3~4",
        "room": "法1F04",
        "credit": "2",
        "limit": 75,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": "1.法律學系學生選讀，不列入通識教育畢業學分數 2.加簽的同學，不用來信，請第一堂課，到教室登記。"
    },
    {
        "id": "U4080",
        "name": "親密關係情感教育",
        "teacher": "蘇柏文",
        "dim": "向度二",
        "time": "每週四7~8",
        "room": "商2F04",
        "credit": "2",
        "limit": 35,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": ""
    },
    {
        "id": "U4088",
        "name": "納粹政權與種族意識型態",
        "teacher": "伍碧雯",
        "dim": "向度六",
        "time": "每週四5~6",
        "room": "",
        "credit": "2",
        "limit": 40,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "教室請儘量排社科院2F02教室; 歷史系學生選讀,不列入其通識畢業學分數(111學年度起調整為向度六) 伍碧雯老師通識課程完全由學校電腦決定學生名單，不接受人工加簽。請同學不要寫e-mail詢問老師。"
    },
    {
        "id": "U4090",
        "name": "電影理論與賞析",
        "teacher": "蔡月娥",
        "dim": "向度一",
        "time": "每週二3~4",
        "room": "文4F07",
        "credit": "2",
        "limit": 55,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "1.請安排於人文4F07教室"
    },
    {
        "id": "U4099",
        "name": "音樂劇欣賞",
        "teacher": "涂菀凌",
        "dim": "向度一",
        "time": "每週五5~6",
        "room": "商1F01",
        "credit": "2",
        "limit": 50,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": "請安排商１０１。原「古典音樂賞析」更名。"
    },
    {
        "id": "U4112",
        "name": "財政、租稅與公民",
        "teacher": "鄧軫元",
        "dim": "向度三",
        "time": "每週三5~6",
        "room": "法1F19",
        "credit": "2",
        "limit": 120,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": "財政系學生選讀，不列入其通識畢業學分數。"
    },
    {
        "id": "U4116",
        "name": "人類學觀點下的未來城市",
        "teacher": "楊明浩",
        "dim": "向度四",
        "time": "每週四5~6",
        "room": "",
        "credit": "2",
        "limit": 33,
        "enrolled": 0,
        "can_add": "否",
        "lang": "英語 English",
        "note": ""
    },
    {
        "id": "U4117",
        "name": "編輯設計與數位出版學",
        "teacher": "雷碧秀",
        "dim": "向度一",
        "time": "每週一7~8",
        "room": "社114_互動",
        "credit": "2",
        "limit": 40,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": ""
    },
    {
        "id": "U4127",
        "name": "從影像看中國",
        "teacher": "李訓詳",
        "dim": "向度六",
        "time": "每週三7~8",
        "room": "",
        "credit": "2",
        "limit": 40,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "曾修習過 「歷史-從影像看中國 」的同學，不得再修習此課程。歷史系學生選讀，不列入其通識畢業學分數。"
    },
    {
        "id": "U4135",
        "name": "媒體與社會化",
        "teacher": "黃薏文",
        "dim": "向度四",
        "time": "每週一7~8",
        "room": "社203",
        "credit": "2",
        "limit": 50,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "請安排社203"
    },
    {
        "id": "U4145",
        "name": "西洋古典音樂賞析",
        "teacher": "涂菀凌",
        "dim": "向度一",
        "time": "每週五7~8",
        "room": "商1F01",
        "credit": "2",
        "limit": 50,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": "請安排商１０１。"
    },
    {
        "id": "U4152",
        "name": "校園植物認識",
        "teacher": "陳湘繁",
        "dim": "向度五",
        "time": "每週二5~6",
        "room": "公2F05",
        "credit": "2",
        "limit": 25,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "請安排教室\"公114\"。"
    },
    {
        "id": "U4162",
        "name": "當代世界議題：社會、文化與永續未來",
        "teacher": "塔瑪娜",
        "dim": "向度四",
        "time": "每週二3~4",
        "room": "",
        "credit": "2",
        "limit": 26,
        "enrolled": 0,
        "can_add": "否",
        "lang": "英語 English",
        "note": ""
    },
    {
        "id": "U4173",
        "name": "歐洲聯盟：跨國法律與政策",
        "teacher": "曾秀珍",
        "dim": "向度三",
        "time": "每週五5~6",
        "room": "社112",
        "credit": "2",
        "limit": 50,
        "enrolled": 0,
        "can_add": "是",
        "lang": "英語 English",
        "note": "英文課程。請安排社科112 教室。"
    },
    {
        "id": "U4176",
        "name": "生態台灣",
        "teacher": "陳湘繁",
        "dim": "向度五",
        "time": "每週二3~4",
        "room": "公1F14",
        "credit": "2",
        "limit": 60,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "請安排教室\"公114\"。"
    },
    {
        "id": "U4185",
        "name": "歐美現代小說欣賞",
        "teacher": "張懿仁",
        "dim": "向度一",
        "time": "每週三3~4",
        "room": "",
        "credit": "2",
        "limit": 30,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "應外系學生修習不列入通識畢業學分。"
    },
    {
        "id": "U4188",
        "name": "自然科學與當代世界",
        "teacher": "柯賢真",
        "dim": "向度五",
        "time": "每週五5~6",
        "room": "電2F03",
        "credit": "2",
        "limit": 40,
        "enrolled": 0,
        "can_add": "是",
        "lang": "英語 English",
        "note": "請優先安排音律電機資訊大樓 204 或 205 教室；若無法安排，則同棟其他教室亦可。"
    },
    {
        "id": "U4189",
        "name": "東南亞多元與發展",
        "teacher": "辛法春",
        "dim": "向度六",
        "time": "每週三5~6",
        "room": "文1F10",
        "credit": "2",
        "limit": 70,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": "曾修習過 「歷史-二戰後的東南亞 」的同學，不得再修習此課程。請安排文110教室,謝謝。"
    },
    {
        "id": "U4194",
        "name": "旅行、文學與地理",
        "teacher": "蔡怡玟",
        "dim": "向度二",
        "time": "每週一1~2",
        "room": "商1F09",
        "credit": "2",
        "limit": 60,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": ""
    },
    {
        "id": "U4200",
        "name": "智慧財產權與社會生活",
        "teacher": "葉斯偉",
        "dim": "向度三",
        "time": "每週一7~8",
        "room": "公1F11",
        "credit": "2",
        "limit": 60,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "法律學院學生選讀，不列入其通識畢業學分數。"
    },
    {
        "id": "U4206",
        "name": "氣象與人生",
        "teacher": "林炯明",
        "dim": "向度五",
        "time": "每週一3~4",
        "room": "電1F03",
        "credit": "2",
        "limit": 50,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "請安排電機資訊大樓教室"
    },
    {
        "id": "U4209",
        "name": "海山地區的藝術與文化創意產業",
        "teacher": "楊凡逸",
        "dim": "向度一",
        "time": "每週二7~8",
        "room": "文2F09",
        "credit": "2",
        "limit": 40,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": ""
    },
    {
        "id": "U4211",
        "name": "自然科學與當代世界",
        "teacher": "柯賢真",
        "dim": "向度五",
        "time": "每週五3~4",
        "room": "電2F03",
        "credit": "2",
        "limit": 40,
        "enrolled": 0,
        "can_add": "是",
        "lang": "英語 English",
        "note": "請優先安排音律電機資訊大樓 204 或 205 教室；若無法安排，則同棟其他教室亦可。"
    },
    {
        "id": "U4214",
        "name": "博物館學導論",
        "teacher": "楊凡逸",
        "dim": "向度一",
        "time": "每週二3~4",
        "room": "",
        "credit": "2",
        "limit": 40,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": ""
    },
    {
        "id": "U4215",
        "name": "個人成長與家庭",
        "teacher": "林維能",
        "dim": "向度二",
        "time": "每週三5~6",
        "room": "文2F10",
        "credit": "2",
        "limit": 30,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": ""
    },
    {
        "id": "U4216",
        "name": "納粹政權與種族意識型態",
        "teacher": "伍碧雯",
        "dim": "向度六",
        "time": "每週一3~4",
        "room": "社202",
        "credit": "2",
        "limit": 40,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "教室請儘量排社科院2F02教室; 歷史系學生選讀,不列入其通識畢業學分數(111學年度起調整為向度六) 伍碧雯老師通識課程完全由學校電腦決定學生名單，不接受人工加簽。請同學不要寫e-mail詢問老師。"
    },
    {
        "id": "U4217",
        "name": "飲食文化",
        "teacher": "辛法春",
        "dim": "向度六",
        "time": "每週二7~8",
        "room": "文2F01",
        "credit": "2",
        "limit": 50,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": "請安排文201教室"
    },
    {
        "id": "U4218",
        "name": "倫理學與當代議題",
        "teacher": "陳莉莉",
        "dim": "向度二",
        "time": "每週五5~6",
        "room": "公1F01",
        "credit": "2",
        "limit": 60,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "原「倫理學」更名。行政系學生選讀，不列入其通識畢業學分數。"
    },
    {
        "id": "U4223",
        "name": "智慧財產權與社會生活",
        "teacher": "葉斯偉",
        "dim": "向度三",
        "time": "每週三7~8",
        "room": "公1F02",
        "credit": "2",
        "limit": 60,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "法律學院學生選讀，不列入其通識畢業學分數。"
    },
    {
        "id": "U4229",
        "name": "淺談地震",
        "teacher": "林炯明",
        "dim": "向度五",
        "time": "每週一1~2",
        "room": "電1F03",
        "credit": "2",
        "limit": 50,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "請安排電機資訊大樓教室"
    },
    {
        "id": "U4232",
        "name": "幸福管理",
        "teacher": "陳澤義",
        "dim": "向度二",
        "time": "每週四5~6",
        "room": "商1F11",
        "credit": "2",
        "limit": 120,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": ""
    },
    {
        "id": "U4234",
        "name": "國際政治與國際關係",
        "teacher": "曾秀珍",
        "dim": "向度四",
        "time": "每週一1~2",
        "room": "社113",
        "credit": "2",
        "limit": 50,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": "行政系學生選讀，不列入其通識畢業學分數。請安排社科112 教室。"
    },
    {
        "id": "U4237",
        "name": "營業秘密與產業創新",
        "teacher": "葉斯偉",
        "dim": "向度四",
        "time": "每週三5~6",
        "room": "公1F02",
        "credit": "2",
        "limit": 60,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": ""
    },
    {
        "id": "U4240",
        "name": "心理健康與自我成長",
        "teacher": "王冠生",
        "dim": "向度二",
        "time": "每週一5~6",
        "room": "文1F11",
        "credit": "2",
        "limit": 105,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "請優先排在人文學院1F11。"
    },
    {
        "id": "U4241",
        "name": "世界文化與永續發展",
        "teacher": "塔瑪娜",
        "dim": "向度四",
        "time": "每週一5~6",
        "room": "公1F12",
        "credit": "2",
        "limit": 26,
        "enrolled": 0,
        "can_add": "否",
        "lang": "英語 English",
        "note": "智永學程學生選修，不列入其通識畢業學分數。"
    },
    {
        "id": "U4242",
        "name": "近代中國的改革開放與競爭衝突",
        "teacher": "羅國暉",
        "dim": "向度六",
        "time": "每週四3~4",
        "room": "",
        "credit": "2",
        "limit": 40,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": ""
    },
    {
        "id": "U4247",
        "name": "公共空間與集體記憶",
        "teacher": "陳香杏",
        "dim": "向度三",
        "time": "每週四3~4",
        "room": "文1F09",
        "credit": "2",
        "limit": 50,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "請安排於文院1F09、2F01、1F10等教室。"
    },
    {
        "id": "U4248",
        "name": "歷史與人物",
        "teacher": "陳香杏",
        "dim": "向度六",
        "time": "每週五5~6",
        "room": "文2F01",
        "credit": "2",
        "limit": 50,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": "請安排於文院1F09、2F01、1F10等教室。歷史系學生選讀者不列入其通識畢業學分數。"
    },
    {
        "id": "U4249",
        "name": "儒釋道與現代生活",
        "teacher": "郭慧娟",
        "dim": "向度二",
        "time": "每週一7~8",
        "room": "文1F10",
        "credit": "2",
        "limit": 30,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "中文系學生選讀，不列入通識畢業學分數。"
    },
    {
        "id": "U4255",
        "name": "口述歷史：理論與實作",
        "teacher": "王超然",
        "dim": "向度六",
        "time": "每週三3~4",
        "room": "文4F07",
        "credit": "2",
        "limit": 40,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": ""
    },
    {
        "id": "U4258",
        "name": "中國近代社會生活史",
        "teacher": "陳香杏",
        "dim": "向度六",
        "time": "每週四5~6",
        "room": "文2F01",
        "credit": "2",
        "limit": 50,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "請安排於文院1F09、2F01、1F10等教室。歷史系學生選讀，不列入其通識畢業學分數。"
    },
    {
        "id": "U4260",
        "name": "衛生保健",
        "teacher": "******",
        "dim": "向度五",
        "time": "每週四5~6",
        "room": "資B1F-02",
        "credit": "2",
        "limit": 45,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "台灣大學遠距課程；時間四13:20~15:00；程劭儀老師；限電腦加退選。"
    },
    {
        "id": "U4263",
        "name": "Python資料科學與人工智慧",
        "teacher": "王孫崇",
        "dim": "向度五",
        "time": "每週五3~4",
        "room": "社201",
        "credit": "2",
        "limit": 60,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": "經濟系、智永學程學生修習不列入通識畢業學分。"
    },
    {
        "id": "U4268",
        "name": "旅行、文學與地理",
        "teacher": "蔡怡玟",
        "dim": "向度二",
        "time": "每週一3~4",
        "room": "商1F09",
        "credit": "2",
        "limit": 60,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": ""
    },
    {
        "id": "U4274",
        "name": "近代中國城市的休閒生活與文化",
        "teacher": "陳香杏",
        "dim": "向度一",
        "time": "每週二5~6",
        "room": "文1F09",
        "credit": "2",
        "limit": 50,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": "請安排於文院1F09、2F01、1F10等教室。歷史系學生選讀，不列入其通識畢業學分數。"
    },
    {
        "id": "U4279",
        "name": "古今司法故事與歷史思維",
        "teacher": "******",
        "dim": "向度六",
        "time": "每週四3~4",
        "room": "文2F09",
        "credit": "2",
        "limit": 40,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "歷史系學生選讀，不列入其通識畢業學分數"
    },
    {
        "id": "U4281",
        "name": "人工智慧導論",
        "teacher": "王孫崇",
        "dim": "向度五",
        "time": "每週四3~4",
        "room": "社101",
        "credit": "2",
        "limit": 60,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": "資工系、電機系、智永學程學生修習不列入通識畢業學分。"
    },
    {
        "id": "U4285",
        "name": "現代西方世界的形成",
        "teacher": "楊子政",
        "dim": "向度六",
        "time": "每週四3~4",
        "room": "",
        "credit": "2",
        "limit": 40,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "歷史系學生修習不列入通識畢業學分"
    },
    {
        "id": "U4298",
        "name": "繪畫藝術與科學方法",
        "teacher": "張舜德",
        "dim": "向度一",
        "time": "每週一5~6",
        "room": "商1F01",
        "credit": "2",
        "limit": 80,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "請安排商1F01教室"
    },
    {
        "id": "U4311",
        "name": "社會面向下的空間與地方創生",
        "teacher": "楊明浩",
        "dim": "向度四",
        "time": "每週三5~6",
        "room": "公1F01",
        "credit": "2",
        "limit": 12,
        "enrolled": 0,
        "can_add": "否",
        "lang": "英語 English",
        "note": "不動產城鄉系及智永學程學生選修，不列入其通識畢業學分數。"
    },
    {
        "id": "U4313",
        "name": "日本政治經濟發展",
        "teacher": "李嘉進",
        "dim": "向度三",
        "time": "每週五5~6",
        "room": "法2F03",
        "credit": "2",
        "limit": 50,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": ""
    },
    {
        "id": "U4328",
        "name": "海山地區的風土飲食與永續實踐",
        "teacher": "林佩欣",
        "dim": "向度四",
        "time": "每週五3~4",
        "room": "文1F10",
        "credit": "2",
        "limit": 35,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": ""
    },
    {
        "id": "U4330",
        "name": "明清小說與社會",
        "teacher": "辛法春",
        "dim": "向度六",
        "time": "每週二3~4",
        "room": "文1F10",
        "credit": "2",
        "limit": 60,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": "請安排文201教室"
    },
    {
        "id": "U4338",
        "name": "職場軟實力",
        "teacher": "******",
        "dim": "向度二",
        "time": "每週四5~6",
        "room": "商1F16",
        "credit": "2",
        "limit": 66,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "此課程授課老師尚未安排."
    },
    {
        "id": "U4344",
        "name": "環境、地理與心理",
        "teacher": "蔡怡玟",
        "dim": "向度一",
        "time": "每週五3~4",
        "room": "商2F08",
        "credit": "2",
        "limit": 60,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": ""
    },
    {
        "id": "U4345",
        "name": "經濟學概論",
        "teacher": "徐芳霞",
        "dim": "向度四",
        "time": "每週三7~8",
        "room": "社107",
        "credit": "2",
        "limit": 34,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": "商學院、經濟系、不動產城鄉系、財政系、智永學程學生選修，不列入其通識畢業學分數。 限修40人。 敬請安排社科107教室。"
    },
    {
        "id": "U4348",
        "name": "大數據下的唐詩",
        "teacher": "楊果霖",
        "dim": "向度五",
        "time": "每週一7~8",
        "room": "文3F11_L",
        "credit": "2",
        "limit": 35,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": "1.請安排於人文3L09L電腦教室 2.中文系學生選讀，不列入通識畢業學分數"
    },
    {
        "id": "U4353",
        "name": "近世中國的社會與文化",
        "teacher": "何淑宜",
        "dim": "向度六",
        "time": "每週四5~6",
        "room": "",
        "credit": "2",
        "limit": 50,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "請排文學院2樓的教室。謝謝。歷史系學生選讀，不列入其通識畢業學分數。"
    },
    {
        "id": "U4354",
        "name": "斯拉夫語言文化概論",
        "teacher": "塔瑪娜",
        "dim": "向度一",
        "time": "每週四5~6",
        "room": "公1F12",
        "credit": "2",
        "limit": 26,
        "enrolled": 0,
        "can_add": "是",
        "lang": "英語 English",
        "note": ""
    },
    {
        "id": "U4356",
        "name": "公共空間與集體記憶",
        "teacher": "陳香杏",
        "dim": "向度三",
        "time": "每週二3~4",
        "room": "文1F09",
        "credit": "2",
        "limit": 50,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "請安排於文院1F09、2F01、1F10等教室。"
    },
    {
        "id": "U4360",
        "name": "世界遺產巡禮",
        "teacher": "王淳熙",
        "dim": "向度六",
        "time": "每週二7~8",
        "room": "文2F08",
        "credit": "2",
        "limit": 60,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "歷史系學生選讀，不列入其通識畢業學分數。 加簽時限已修習「文化與觀光學士學分學程與微學程」、「歷史實踐與文化資產學分學程與微學程」之同學。"
    },
    {
        "id": "U4365",
        "name": "當代民主思潮",
        "teacher": "張朝琴",
        "dim": "向度三",
        "time": "每週五3~4",
        "room": "社102",
        "credit": "2",
        "limit": 60,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "行政系學生選讀，不列入其通識畢業學分數。"
    },
    {
        "id": "U4366",
        "name": "語言與文化",
        "teacher": "陳淑惠",
        "dim": "向度一",
        "time": "每週二7~8",
        "room": "公2F35_互動",
        "credit": "2",
        "limit": 40,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "應外系學生選讀，不列入通識教育畢業學分數。請安排社203"
    },
    {
        "id": "U4367",
        "name": "生命教育",
        "teacher": "王冠生",
        "dim": "向度二",
        "time": "每週一7~8",
        "room": "文1F11",
        "credit": "2",
        "limit": 100,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "請優先排在人文學院1F11"
    },
    {
        "id": "U4368",
        "name": "絲綢之路與西域藝術文物",
        "teacher": "楊果霖",
        "dim": "向度一",
        "time": "每週一3~4",
        "room": "文2F11",
        "credit": "2",
        "limit": 35,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": ""
    },
    {
        "id": "U4369",
        "name": "勞工福利與移工問題",
        "teacher": "張朝琴",
        "dim": "向度四",
        "time": "每週五5~6",
        "room": "社102",
        "credit": "2",
        "limit": 60,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": ""
    },
    {
        "id": "U4375",
        "name": "數位傳播與人文藝術",
        "teacher": "******",
        "dim": "向度四",
        "time": "每週一8~9",
        "room": "資1F-08",
        "credit": "2",
        "limit": 40,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "政治大學主播遠距課程；黃葳威老師；限電腦加退選。"
    },
    {
        "id": "U4376",
        "name": "運動與健康",
        "teacher": "林啟賢",
        "dim": "向度五",
        "time": "每週二3~4",
        "room": "社112",
        "credit": "2",
        "limit": 60,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": "休運系學生選讀，不列入其通識畢業學分數。"
    },
    {
        "id": "U4378",
        "name": "視覺藝術",
        "teacher": "吳國淳",
        "dim": "向度一",
        "time": "每週二3~4",
        "room": "第二教室社203",
        "credit": "2",
        "limit": 45,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "希望安排在法學院教室217或213; 第二教室請設社203"
    },
    {
        "id": "U4379",
        "name": "中國近代社會生活史",
        "teacher": "陳香杏",
        "dim": "向度六",
        "time": "每週五3~4",
        "room": "文2F01",
        "credit": "2",
        "limit": 50,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "請安排於文院1F09、2F01、1F10等教室。歷史系學生選讀，不列入其通識畢業學分數。"
    },
    {
        "id": "U4381",
        "name": "食在拉丁美洲：歷史與文化",
        "teacher": "褚縈瑩",
        "dim": "向度六",
        "time": "每週二7~8",
        "room": "文2F07",
        "credit": "2",
        "limit": 40,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": ""
    },
    {
        "id": "U4389",
        "name": "絲綢之路與西域藝術文物",
        "teacher": "楊果霖",
        "dim": "向度一",
        "time": "每週一5~6",
        "room": "商2F12",
        "credit": "2",
        "limit": 35,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": ""
    },
    {
        "id": "U4394",
        "name": "生成式人工智慧應用實務",
        "teacher": "黃振益",
        "dim": "向度五",
        "time": "每週三3~4",
        "room": "資B1F-01",
        "credit": "2",
        "limit": 60,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": "資工系學生修習不列入通識畢業學分。"
    },
    {
        "id": "U4396",
        "name": "AI × Vibe Coding：無痛入門創意自動化開發",
        "teacher": "黃振益",
        "dim": "向度五",
        "time": "每週三5~6",
        "room": "資B1F-01",
        "credit": "2",
        "limit": 60,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": ""
    },
    {
        "id": "U4398",
        "name": "影像、閱讀與現代臺灣",
        "teacher": "胡清暉",
        "dim": "向度一",
        "time": "每週二5~6",
        "room": "社102",
        "credit": "2",
        "limit": 60,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": ""
    },
    {
        "id": "U4405",
        "name": "消費者保護法與現代社會",
        "teacher": "葉斯偉",
        "dim": "向度三",
        "time": "每週一5~6",
        "room": "公1F11",
        "credit": "2",
        "limit": 60,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "法律系、金融系學生選讀，不列入其通識畢業學分數。"
    },
    {
        "id": "U4406",
        "name": "傳播與文化",
        "teacher": "雷碧秀",
        "dim": "向度三",
        "time": "每週一1~2",
        "room": "社114_互動",
        "credit": "2",
        "limit": 50,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": ""
    },
    {
        "id": "U4407",
        "name": "新媒體之媒體識讀",
        "teacher": "雷碧秀",
        "dim": "向度三",
        "time": "每週一3~4",
        "room": "社114_互動",
        "credit": "2",
        "limit": 50,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": ""
    },
    {
        "id": "U4408",
        "name": "藥物安全教育",
        "teacher": "張朝琴",
        "dim": "向度五",
        "time": "每週五7~8",
        "room": "社102",
        "credit": "2",
        "limit": 60,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": ""
    },
    {
        "id": "U4409",
        "name": "臺法工藝文化探索",
        "teacher": "曾秀珍",
        "dim": "向度四",
        "time": "每週五7~8",
        "room": "社112",
        "credit": "2",
        "limit": 50,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": "請安排社科112 教室。"
    },
    {
        "id": "U4411",
        "name": "環境倫理學",
        "teacher": "林炯明",
        "dim": "向度二",
        "time": "每週一5~6",
        "room": "電2F01",
        "credit": "2",
        "limit": 50,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "請安排電機資訊大樓教室"
    },
    {
        "id": "U4412",
        "name": "現代藝術與美學",
        "teacher": "吳國淳",
        "dim": "向度一",
        "time": "每週一3~4",
        "room": "第二教室社203",
        "credit": "2",
        "limit": 45,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "希望安排在法學院教室217或213; 第二教室請設社203"
    },
    {
        "id": "U4413",
        "name": "從0開始的創業入門",
        "teacher": "江振宇",
        "dim": "向度四",
        "time": "每週三5~6",
        "room": "",
        "credit": "2",
        "limit": 50,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": "上課教室：創新創業中心（圖書館後方B1)"
    },
    {
        "id": "U4419",
        "name": "人機傳播實戰：AI、網紅和社群社會",
        "teacher": "許智超",
        "dim": "向度三",
        "time": "每週一5~6",
        "room": "電1F04",
        "credit": "2",
        "limit": 60,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": "請協助安排音律電機資訊大樓教室"
    },
    {
        "id": "U4420",
        "name": "行動媒體科技探索實作",
        "teacher": "許智超",
        "dim": "向度五",
        "time": "每週一7~8",
        "room": "電1F04",
        "credit": "2",
        "limit": 60,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": "請協助安排音律電機資訊大樓教室"
    },
    {
        "id": "U4421",
        "name": "都市地理與地方創生",
        "teacher": "蔡怡玟",
        "dim": "向度四",
        "time": "每週五5~6",
        "room": "社203",
        "credit": "2",
        "limit": 60,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": "請安排社203。不動產城鄉系學生選讀，不列入其通識畢業學分。"
    },
    {
        "id": "U4424",
        "name": "書法藝術之美",
        "teacher": "鍾叡逸",
        "dim": "向度一",
        "time": "每週四7~8",
        "room": "",
        "credit": "2",
        "limit": 45,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "中文系學生選讀，不列入通識教育畢業學分數。請安排至人文大樓109書法教室，謝謝。"
    },
    {
        "id": "U4001",
        "name": "Python資料科學-公共事務與法學應用",
        "teacher": "楊喨智",
        "dim": "向度五",
        "time": "每週四7~9",
        "room": "資1F-09",
        "credit": "3",
        "limit": 50,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "1.與法學院(20人)及犯研所(10人)合班。 2.請安排資1F-09或資B1F-04電腦教室(包括TA需82人座)"
    },
    {
        "id": "U4017",
        "name": "華語教學方法與實務",
        "teacher": "陳淑惠",
        "dim": "向度一",
        "time": "每週三5~7",
        "room": "社203",
        "credit": "3",
        "limit": 45,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": "中文系學生選讀，不列入通識教育畢業學分數。請安排社203"
    },
    {
        "id": "U4035",
        "name": "綠木家具設計實務",
        "teacher": "趙南開",
        "dim": "向度一",
        "time": "每週一2~4",
        "room": "木101",
        "credit": "3",
        "limit": 24,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": "請安排木藝教室。本課程需自行操作木工機具，自費購買木料 。"
    },
    {
        "id": "U4068",
        "name": "性別與休閒",
        "teacher": "蔡瓊姿",
        "dim": "向度四",
        "time": "每週四2~4",
        "room": "",
        "credit": "3",
        "limit": 30,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "休運系學生選讀，不列入其通識畢業學分數。"
    },
    {
        "id": "U4113",
        "name": "藝術輔療與高齡社會服務",
        "teacher": "林子晴 劉素芬",
        "dim": "向度一",
        "time": "每週四2~4",
        "room": "社203",
        "credit": "3",
        "limit": 20,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "社工系學生選讀，不列入其通識畢業學分。原「藝術輔療與高齡社會工作」更名。"
    },
    {
        "id": "U4132",
        "name": "綠木家具設計實務",
        "teacher": "趙南開",
        "dim": "向度一",
        "time": "每週一6~8",
        "room": "木101",
        "credit": "3",
        "limit": 8,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": "請安排木藝教室。本課程需自行操作木工機具，自費購買木料 。"
    },
    {
        "id": "U4146",
        "name": "西方古典音樂賞析與AI實作",
        "teacher": "林子晴 楊喨智",
        "dim": "向度一",
        "time": "每週五5~7",
        "room": "資B1F-04",
        "credit": "3",
        "limit": 40,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": ""
    },
    {
        "id": "U4202",
        "name": "生活陶的應用與實作",
        "teacher": "林佩欣",
        "dim": "向度一",
        "time": "每週一5~7",
        "room": "",
        "credit": "3",
        "limit": 20,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": ""
    },
    {
        "id": "U4212",
        "name": "環保犯罪學",
        "teacher": "陳湘繁 黃蘭媖",
        "dim": "向度三",
        "time": "每週一5~7",
        "room": "公2F06",
        "credit": "3",
        "limit": 25,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "本課程為通識中心、犯罪所和資源所的並列課程，陳湘繁與黃蘭�漲悎v共授。"
    },
    {
        "id": "U4236",
        "name": "現代東亞",
        "teacher": "羅國暉",
        "dim": "向度六",
        "time": "每週二5~7",
        "room": "",
        "credit": "3",
        "limit": 40,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": ""
    },
    {
        "id": "U4297",
        "name": "日本近代史",
        "teacher": "蔡龍保",
        "dim": "向度六",
        "time": "每週四5~7",
        "room": "文1F09",
        "credit": "3",
        "limit": 25,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "本課程為歷史系選修及通識的並列課程，請同學依需求選擇課程與課號。"
    },
    {
        "id": "U4321",
        "name": "個人理財",
        "teacher": "陳達新",
        "dim": "向度四",
        "time": "每週二5~7",
        "room": "",
        "credit": "3",
        "limit": 50,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "金融系、統計系學生修習不列入通識畢業學分"
    },
    {
        "id": "U4341",
        "name": "社會科學研究的AI科技應用",
        "teacher": "楊喨智 陳婉琪",
        "dim": "向度五",
        "time": "每週一5~7",
        "room": "資1F-14",
        "credit": "3",
        "limit": 10,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "社會系學生選讀，不列入其通識畢業學分數。本課程為通識中心、社會系所的並列課程，陳婉琪老師與楊喨智老師共授。"
    },
    {
        "id": "U4351",
        "name": "國際政治經濟學：理論與實踐",
        "teacher": "鄭又平 蘇軍瑋",
        "dim": "向度四",
        "time": "每週三5~7",
        "room": "社B02",
        "credit": "3",
        "limit": 130,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": "行政系學生選修者，不列入其通識畢業學分,亦不列入選修學分(擬採計為選修學分者，請改選行政系選修流水碼). 本學期課程由鄭又平及蘇軍瑋老師共同授課。"
    }
];
