const rawData = [
    {
        "id": "U4023",
        "name": "閱讀與人生探索",
        "teacher": "陳淑惠",
        "dim": "向度二",
        "time": "每週五5~7",
        "room": "",
        "credit": "1",
        "limit": 30,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": "本課程為密集課程。實際上課時間請詳閱課程大綱。請至圖書館6F會議室上課。"
    },
    {
        "id": "U2002",
        "name": "情緒管理與壓力調適",
        "teacher": "吳國淳",
        "dim": "向度二",
        "time": "每週一3~4",
        "room": "法2F13",
        "credit": "2",
        "limit": 40,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": "此為大學入門課程，志願選課階段限1、2年級選讀，加退選階段開放所有年級選讀。總人數限制為45人。希望安排在法學院教室"
    },
    {
        "id": "U2010",
        "name": "時代與歷史",
        "teacher": "何淑宜",
        "dim": "向度六",
        "time": "每週四5~6",
        "room": "文2F10",
        "credit": "2",
        "limit": 30,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "教室請安排人文學院。歷史系學生選讀者不列入其通識畢業學分數。此為大學入門課程，志願選課階段限1、2年級選讀，加退選階段開放所有年級選讀。總人數限制40人。"
    },
    {
        "id": "U2029",
        "name": "生物多樣性",
        "teacher": "陳湘繁",
        "dim": "向度五",
        "time": "每週一3~4",
        "room": "公1F14",
        "credit": "2",
        "limit": 50,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "此為大學入門課程，志願選課階段限1、2年級選讀，加退選階段開放所有年級選讀。總人數限制為60人。請安排教室\"公114\"。"
    },
    {
        "id": "U2066",
        "name": "全球化與多元文化",
        "teacher": "曾秀珍",
        "dim": "向度四",
        "time": "每週一3~4",
        "room": "社112",
        "credit": "2",
        "limit": 40,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": "此為大學入門課程，志願選課階段限1、2年級選讀，加退選階段開放所有年級選讀。總人數限制為50人。請安排 社101。"
    },
    {
        "id": "U2129",
        "name": "文學詮釋與生命哲學",
        "teacher": "吳惠玲",
        "dim": "向度一",
        "time": "每週二3~4",
        "room": "文1F11",
        "credit": "2",
        "limit": 70,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "1.請安排於人文1F11教室 2.中文系學生選讀，不列入通識畢業學分數。 3.此為大學入門課程，志願選課階段限一、二年級70人選修，加退選階段開放所有年級選修，總限修人數90人。 4.原「文學與人生」更名，請勿重複修讀。"
    },
    {
        "id": "U2130",
        "name": "情緒管理與壓力調適",
        "teacher": "吳國淳",
        "dim": "向度二",
        "time": "每週二5~6",
        "room": "法2F13",
        "credit": "2",
        "limit": 40,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": "此為大學入門課程，志願選課階段限1、2年級選讀，加退選階段開放所有年級選讀。總人數限制為45人。希望安排在法學院教室"
    },
    {
        "id": "U4001",
        "name": "網路生活應用",
        "teacher": "溫演福",
        "dim": "向度五",
        "time": "每週二3~4",
        "room": "法2F27",
        "credit": "2",
        "limit": 75,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": ""
    },
    {
        "id": "U4002",
        "name": "運算思維與程式設計",
        "teacher": "許銘芳",
        "dim": "向度五",
        "time": "每週五3~4",
        "room": "資1F-10",
        "credit": "2",
        "limit": 50,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": "資工系、企管系學生選讀，不列入其通識畢業學分數。"
    },
    {
        "id": "U4003",
        "name": "居家環境與風水文化",
        "teacher": "林秋綿",
        "dim": "向度二",
        "time": "每週三5~6",
        "room": "公2F36",
        "credit": "2",
        "limit": 80,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "不動產城鄉系學生不列入通識學分，亦不可列入外系選修學分。曾修過不動產城鄉系「居家風水概論」者，請勿重複修習。"
    },
    {
        "id": "U4005",
        "name": "書法藝術之美",
        "teacher": "鍾叡逸",
        "dim": "向度一",
        "time": "每週二7~8",
        "room": "文1F09",
        "credit": "2",
        "limit": 45,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "中文系學生選讀，不列入通識教育畢業學分數。請安排至人文大樓109書法教室，謝謝。"
    },
    {
        "id": "U4006",
        "name": "飲食文化",
        "teacher": "辛法春",
        "dim": "向度六",
        "time": "每週二7~8",
        "room": "文2F01",
        "credit": "2",
        "limit": 60,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": "教室請安排文2F01，謝謝。自113學年度起調整為向度六。"
    },
    {
        "id": "U4011",
        "name": "海山地區的歷史、文化與創生",
        "teacher": "林佩欣",
        "dim": "向度六",
        "time": "每週三3~4",
        "room": "文2F08",
        "credit": "2",
        "limit": 50,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": ""
    },
    {
        "id": "U4013",
        "name": "國際禮儀與文化",
        "teacher": "藍蕾",
        "dim": "向度一",
        "time": "每週二3~4",
        "room": "文4F05_L",
        "credit": "2",
        "limit": 30,
        "enrolled": 0,
        "can_add": "否",
        "lang": "英語 English",
        "note": "應外系學生選讀，不列入其通識畢業學分數。英語授課，建議英文程度為全民英檢中級(含)以上者選修。 麻煩安排人文4F05教室"
    },
    {
        "id": "U4016",
        "name": "歌謠臺灣史",
        "teacher": "許嘉瑋",
        "dim": "向度六",
        "time": "每週三7~8",
        "room": "文2F09",
        "credit": "2",
        "limit": 35,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "中文系學生選讀，不列入通識畢業學分數。"
    },
    {
        "id": "U4017",
        "name": "都市設計思維的基礎",
        "teacher": "楊明浩",
        "dim": "向度四",
        "time": "每週二5~6",
        "room": "公1F10",
        "credit": "2",
        "limit": 30,
        "enrolled": 0,
        "can_add": "否",
        "lang": "英語 English",
        "note": "不動產城鄉系學生修習者,不列入其通識畢業學分。"
    },
    {
        "id": "U4021",
        "name": "西洋詩歌概論",
        "teacher": "林熙強",
        "dim": "向度一",
        "time": "每週五3~4",
        "room": "文1F11",
        "credit": "2",
        "limit": 40,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "1.請安排於人文111教室。 2.應外系學生選讀，不列入其通識畢業學分數。"
    },
    {
        "id": "U4026",
        "name": "斯拉夫語言文化概論",
        "teacher": "塔瑪娜",
        "dim": "向度一",
        "time": "每週四5~6",
        "room": "公1F04",
        "credit": "2",
        "limit": 30,
        "enrolled": 0,
        "can_add": "否",
        "lang": "英語 English",
        "note": "教室建議可以在公1F04"
    },
    {
        "id": "U4027",
        "name": "納粹政權與種族意識型態",
        "teacher": "伍碧雯",
        "dim": "向度六",
        "time": "每週一3~4",
        "room": "社113",
        "credit": "2",
        "limit": 40,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "請排社科院教室，謝謝。歷史系學生選讀，不列入其通識畢業學分數。 伍碧雯老師通識課程完全由學校電腦決定學生名單，不接受人工加簽。請同學不要寫e-mail詢問老師。"
    },
    {
        "id": "U4028",
        "name": "近代中國的改革開放與競爭衝突",
        "teacher": "羅國暉",
        "dim": "向度六",
        "time": "每週二3~4",
        "room": "文2F12",
        "credit": "2",
        "limit": 40,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": "教室安排，第一順位文院202室 (或其他設有兩台投影機的教室)，或人文學院的二樓教室。"
    },
    {
        "id": "U4029",
        "name": "納粹政權與種族意識型態",
        "teacher": "伍碧雯",
        "dim": "向度六",
        "time": "每週四5~6",
        "room": "社112",
        "credit": "2",
        "limit": 40,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "請排社科院教室，謝謝 歷史系學生選讀,不列入其通識畢業學分數。 伍碧雯老師通識課程完全由學校電腦決定學生名單，不接受人工加簽。請同學不要寫e-mail詢問老師。"
    },
    {
        "id": "U4031",
        "name": "道家文化",
        "teacher": "陳伯軒",
        "dim": "向度二",
        "time": "每週四3~4",
        "room": "文2F10",
        "credit": "2",
        "limit": 40,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "1.請安排於人文2F08教室。 2.中文系學生選讀，不列入其通識畢業學分數。"
    },
    {
        "id": "U4038",
        "name": "心理健康與自我成長",
        "teacher": "王冠生",
        "dim": "向度二",
        "time": "每週一5~6",
        "room": "文1F11",
        "credit": "2",
        "limit": 105,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "請優先排在人文學院1F11"
    },
    {
        "id": "U4040",
        "name": "海山地區的人文與藝術",
        "teacher": "洪健榮",
        "dim": "向度一",
        "time": "每週四7~8",
        "room": "文2F08",
        "credit": "2",
        "limit": 60,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": "人工加簽限收10名"
    },
    {
        "id": "U4042",
        "name": "西洋建築之美賞析",
        "teacher": "王淳熙",
        "dim": "向度一",
        "time": "每週三3~4",
        "room": "文2F07",
        "credit": "2",
        "limit": 60,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": ""
    },
    {
        "id": "U4044",
        "name": "創新與創業",
        "teacher": "江振宇",
        "dim": "向度四",
        "time": "每週三5~6",
        "room": "",
        "credit": "2",
        "limit": 50,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "上課教室：創新創業中心（圖書館後方B1)"
    },
    {
        "id": "U4045",
        "name": "財政、租稅與公民",
        "teacher": "鄧軫元",
        "dim": "向度三",
        "time": "每週三5~6",
        "room": "法1F19",
        "credit": "2",
        "limit": 120,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": "財政系學生選讀，不列入其通識畢業學分數。113.2.27起上課教室改為法1F19"
    },
    {
        "id": "U4050",
        "name": "媒體與公關",
        "teacher": "胡清暉",
        "dim": "向度四",
        "time": "每週二5~6",
        "room": "社105",
        "credit": "2",
        "limit": 60,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "數位行銷學系學生選讀，不列入其通識畢業學分。"
    },
    {
        "id": "U4055",
        "name": "二十世紀德國史",
        "teacher": "伍碧雯",
        "dim": "向度六",
        "time": "每週四3~4",
        "room": "社112",
        "credit": "2",
        "limit": 40,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "請排社科院教室，謝謝。歷史系學生選讀,不列入其通識畢業學分數。 伍碧雯老師通識課程完全由學校電腦決定學生名單，不接受人工加簽。請同學不要寫e-mail詢問老師。"
    },
    {
        "id": "U4057",
        "name": "電影與人生的對話",
        "teacher": "許珮馨",
        "dim": "向度一",
        "time": "每週二3~4",
        "room": "文4F09",
        "credit": "2",
        "limit": 40,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "1.請安排於人文1F11教室 2.應外系學生選讀，不列入其通識畢業學分數。"
    },
    {
        "id": "U4061",
        "name": "媒體與社會化",
        "teacher": "黃薏文",
        "dim": "向度四",
        "time": "每週三7~8",
        "room": "社203",
        "credit": "2",
        "limit": 50,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": ""
    },
    {
        "id": "U4067",
        "name": "環境、地理與心理",
        "teacher": "蔡怡玟",
        "dim": "向度一",
        "time": "每週一3~4",
        "room": "社203",
        "credit": "2",
        "limit": 60,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": "請安排社203翻轉教室。"
    },
    {
        "id": "U4069",
        "name": "生命教育",
        "teacher": "王冠生",
        "dim": "向度二",
        "time": "每週一7~8",
        "room": "文1F11",
        "credit": "2",
        "limit": 105,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "請優先排在人文學院1F11"
    },
    {
        "id": "U4070",
        "name": "中國文化史：生活、禮俗與宗教",
        "teacher": "李訓詳",
        "dim": "向度六",
        "time": "每週四5~6",
        "room": "文2F07",
        "credit": "2",
        "limit": 60,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "歷史系學生選讀者不列入其通識畢業學分數。"
    },
    {
        "id": "U4071",
        "name": "運動與健康",
        "teacher": "林啟賢",
        "dim": "向度五",
        "time": "每週二3~4",
        "room": "社112",
        "credit": "2",
        "limit": 60,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": "休運系學生選讀，不列入其通識畢業學分數。"
    },
    {
        "id": "U4072",
        "name": "中國近代社會生活史",
        "teacher": "陳香杏",
        "dim": "向度六",
        "time": "每週四5~6",
        "room": "文1F09",
        "credit": "2",
        "limit": 50,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "請安排於文院1F09、2F01、1F10等教室。歷史系學生選讀，不列入其通識畢業學分數。"
    },
    {
        "id": "U4076",
        "name": "經濟學概論",
        "teacher": "徐芳霞",
        "dim": "向度四",
        "time": "每週三7~8",
        "room": "社107",
        "credit": "2",
        "limit": 34,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": "商學院、經濟系、不動產城鄉系、財政系、智永學程學生選修，不列入通識畢業學分數。 限修40人。 敬請安排社科107教室。"
    },
    {
        "id": "U4077",
        "name": "中國近現代歷史人物",
        "teacher": "王超然",
        "dim": "向度六",
        "time": "每週四3~4",
        "room": "文4F09",
        "credit": "2",
        "limit": 50,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": "歷史系學生選讀,不列入其通識畢業學分數。"
    },
    {
        "id": "U4087",
        "name": "你要去哪裡?穿梭歐洲的城市",
        "teacher": "楊明浩",
        "dim": "向度四",
        "time": "每週三5~6",
        "room": "公1F10",
        "credit": "2",
        "limit": 35,
        "enrolled": 0,
        "can_add": "否",
        "lang": "英語 English",
        "note": ""
    },
    {
        "id": "U4089",
        "name": "歐洲永續文化首都",
        "teacher": "塔瑪娜",
        "dim": "向度四",
        "time": "每週二5~6",
        "room": "公1F04",
        "credit": "2",
        "limit": 30,
        "enrolled": 0,
        "can_add": "否",
        "lang": "英語 English",
        "note": ""
    },
    {
        "id": "U4090",
        "name": "食在拉丁美洲：歷史與文化",
        "teacher": "褚縈瑩",
        "dim": "向度六",
        "time": "每週二7~8",
        "room": "文2F11",
        "credit": "2",
        "limit": 40,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": ""
    },
    {
        "id": "U4098",
        "name": "公共空間與集體記憶",
        "teacher": "陳香杏",
        "dim": "向度三",
        "time": "每週二3~4",
        "room": "文1F09",
        "credit": "2",
        "limit": 50,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "請安排於文院1F09、2F01、1F10等教室。"
    },
    {
        "id": "U4100",
        "name": "健康促進與體重控制",
        "teacher": "翁仲邦",
        "dim": "向度五",
        "time": "每週三3~4",
        "room": "公1F14",
        "credit": "2",
        "limit": 60,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": "休運系學生選讀，不列入通識教育畢業學分數。"
    },
    {
        "id": "U4101",
        "name": "歷史與人物",
        "teacher": "陳香杏",
        "dim": "向度六",
        "time": "每週五5~6",
        "room": "文2F01",
        "credit": "2",
        "limit": 50,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "請安排於文院1F09、2F01、1F10等教室。歷史系學生選讀者不列入其通識畢業學分數。"
    },
    {
        "id": "U4105",
        "name": "東南亞多元與發展",
        "teacher": "辛法春",
        "dim": "向度六",
        "time": "每週三5~6",
        "room": "文1F10",
        "credit": "2",
        "limit": 75,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": "教室請安排文2F01，謝謝。"
    },
    {
        "id": "U4111",
        "name": "AI時代的思維革命：人工智慧如何影響我們的未來",
        "teacher": "柯賢真",
        "dim": "向度五",
        "time": "每週五3~4",
        "room": "電2F04",
        "credit": "2",
        "limit": 40,
        "enrolled": 0,
        "can_add": "否",
        "lang": "英語 English",
        "note": "請優先安排音律電機資訊大樓 204 或 205 教室。"
    },
    {
        "id": "U4121",
        "name": "金融科技創新與應用",
        "teacher": "楊喨智",
        "dim": "向度四",
        "time": "每週四5~6",
        "room": "資B1F-04",
        "credit": "2",
        "limit": 60,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": "經濟系、智永學程學生修習不列入通識畢業學分數。"
    },
    {
        "id": "U4159",
        "name": "美國檢警制度概論",
        "teacher": "林茂弘",
        "dim": "向度三",
        "time": "每週二5~6",
        "room": "社112",
        "credit": "2",
        "limit": 60,
        "enrolled": 0,
        "can_add": "否",
        "lang": "英語 English",
        "note": "英語授課。"
    },
    {
        "id": "U4169",
        "name": "文化創意產業",
        "teacher": "雷碧秀",
        "dim": "向度四",
        "time": "每週一5~6",
        "room": "社206",
        "credit": "2",
        "limit": 40,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": ""
    },
    {
        "id": "U4186",
        "name": "編輯設計與數位出版學",
        "teacher": "雷碧秀",
        "dim": "向度一",
        "time": "每週一7~8",
        "room": "社206",
        "credit": "2",
        "limit": 40,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": ""
    },
    {
        "id": "U4192",
        "name": "AI時代的思維革命：人工智慧如何影響我們的未來",
        "teacher": "柯賢真",
        "dim": "向度五",
        "time": "每週五5~6",
        "room": "電2F04",
        "credit": "2",
        "limit": 40,
        "enrolled": 0,
        "can_add": "否",
        "lang": "英語 English",
        "note": "請優先安排音律電機資訊大樓 204 或 205 教室。"
    },
    {
        "id": "U4197",
        "name": "日本政治經濟發展",
        "teacher": "李嘉進",
        "dim": "向度三",
        "time": "每週五5~6",
        "room": "公1F11",
        "credit": "2",
        "limit": 50,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": ""
    },
    {
        "id": "U4199",
        "name": "公共空間與集體記憶",
        "teacher": "陳香杏",
        "dim": "向度三",
        "time": "每週四3~4",
        "room": "文1F10",
        "credit": "2",
        "limit": 50,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "請安排於文院1F09、2F01、1F10等教室。"
    },
    {
        "id": "U4200",
        "name": "繪畫藝術與科學方法",
        "teacher": "張舜德",
        "dim": "向度一",
        "time": "每週一5~6",
        "room": "商1F02",
        "credit": "2",
        "limit": 80,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "上課教室請安排商1F02；第一堂課請務必到場"
    },
    {
        "id": "U4204",
        "name": "精神健康促進",
        "teacher": "蘇柏文",
        "dim": "向度二",
        "time": "每週四7~8",
        "room": "社114",
        "credit": "2",
        "limit": 45,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": ""
    },
    {
        "id": "U4205",
        "name": "歐洲聯盟：跨國法律與政策",
        "teacher": "曾秀珍",
        "dim": "向度三",
        "time": "每週五5~6",
        "room": "社112",
        "credit": "2",
        "limit": 40,
        "enrolled": 0,
        "can_add": "是",
        "lang": "英語 English",
        "note": "請排社科112教室。"
    },
    {
        "id": "U4209",
        "name": "媒體實作與創意思考",
        "teacher": "許智超",
        "dim": "向度四",
        "time": "每週一5~6",
        "room": "電1F04",
        "credit": "2",
        "limit": 60,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": "教室請安排在電機資訊學院。"
    },
    {
        "id": "U4212",
        "name": "漢字文化與生活",
        "teacher": "陳淑惠",
        "dim": "向度一",
        "time": "每週一7~8",
        "room": "社203",
        "credit": "2",
        "limit": 50,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": "原「中國古今文字賞析」更名；中文系學生選讀，不列入通識教育畢業學分數。請安排社203教室"
    },
    {
        "id": "U4215",
        "name": "中國近代社會生活史",
        "teacher": "陳香杏",
        "dim": "向度六",
        "time": "每週二5~6",
        "room": "文1F09",
        "credit": "2",
        "limit": 50,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "請安排於文院1F09、2F01、1F10等教室。歷史系學生選讀，不列入其通識畢業學分數。"
    },
    {
        "id": "U4219",
        "name": "行動媒體科技探索實作",
        "teacher": "許智超",
        "dim": "向度五",
        "time": "每週一7~8",
        "room": "電1F04",
        "credit": "2",
        "limit": 60,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": "教室請安排在電機資訊學院。"
    },
    {
        "id": "U4229",
        "name": "SAS EG巨量數據分析概論",
        "teacher": "陳介然",
        "dim": "向度五",
        "time": "每週五1~2",
        "room": "法2F02",
        "credit": "2",
        "limit": 60,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "1.統計學系學生選讀，不列入通識教育畢業學分數。2.須自備筆記型電腦，並至校園授權軟體網，安裝SAS 9.4版(內有SAS EG)統計軟體(Mac不支援)。"
    },
    {
        "id": "U4234",
        "name": "就業安全政策",
        "teacher": "張朝琴",
        "dim": "向度四",
        "time": "每週五3~4",
        "room": "電1F06",
        "credit": "2",
        "limit": 60,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": ""
    },
    {
        "id": "U4236",
        "name": "藥物安全教育",
        "teacher": "張朝琴",
        "dim": "向度五",
        "time": "每週五1~2",
        "room": "電1F06",
        "credit": "2",
        "limit": 60,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": ""
    },
    {
        "id": "U4245",
        "name": "校園植物認識",
        "teacher": "陳湘繁",
        "dim": "向度五",
        "time": "每週二3~4",
        "room": "公1F14",
        "credit": "2",
        "limit": 25,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "請安排教室\"公114\"。"
    },
    {
        "id": "U4247",
        "name": "設計你的人生",
        "teacher": "王冠生",
        "dim": "向度二",
        "time": "每週二5~6",
        "room": "社203",
        "credit": "2",
        "limit": 50,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "請優先排在社科203(翻轉教室)"
    },
    {
        "id": "U4248",
        "name": "西洋古典音樂賞析",
        "teacher": "涂菀凌",
        "dim": "向度一",
        "time": "每週五7~8",
        "room": "商1F01",
        "credit": "2",
        "limit": 50,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": "請安排商１０１。原「古典音樂賞析」更名。"
    },
    {
        "id": "U4249",
        "name": "音樂劇欣賞",
        "teacher": "涂菀凌",
        "dim": "向度一",
        "time": "每週五5~6",
        "room": "商1F01",
        "credit": "2",
        "limit": 50,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": "請安排商101"
    },
    {
        "id": "U4251",
        "name": "智慧財產權與社會生活",
        "teacher": "葉斯偉",
        "dim": "向度三",
        "time": "每週三7~8",
        "room": "公1F11",
        "credit": "2",
        "limit": 60,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "法律學院學生選讀，不列入其通識畢業學分數。"
    },
    {
        "id": "U4253",
        "name": "海山地區的飲食文化與食物設計",
        "teacher": "林佩欣",
        "dim": "向度四",
        "time": "每週五3~4",
        "room": "文2F09",
        "credit": "2",
        "limit": 40,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": ""
    },
    {
        "id": "U4256",
        "name": "校園植物認識",
        "teacher": "陳湘繁",
        "dim": "向度五",
        "time": "每週二5~6",
        "room": "公2F06",
        "credit": "2",
        "limit": 25,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "請安排教室\"公114\"。"
    },
    {
        "id": "U4258",
        "name": "李梅樹文化英文導覽（二）",
        "teacher": "楊凡逸",
        "dim": "向度六",
        "time": "每週二5~6",
        "room": "文4F08",
        "credit": "2",
        "limit": 40,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": ""
    },
    {
        "id": "U4260",
        "name": "近代中國城市的休閒生活與文化",
        "teacher": "陳香杏",
        "dim": "向度一",
        "time": "每週五3~4",
        "room": "文2F01",
        "credit": "2",
        "limit": 50,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "請安排於文院1F09、2F01、1F10等教室。歷史系學生選讀，不列入其通識畢業學分數。"
    },
    {
        "id": "U4261",
        "name": "兩岸關係與國際政治",
        "teacher": "鄭又平",
        "dim": "向度三",
        "time": "每週三5~6",
        "room": "電1F01",
        "credit": "2",
        "limit": 110,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": "「兩岸關係專題」更名； 行政系學生選讀者，不列入其通識畢業學分,亦不列入選修學分(擬修習者請改選行政系選修流水碼)."
    },
    {
        "id": "U4263",
        "name": "倫理學與當代議題",
        "teacher": "陳莉莉",
        "dim": "向度二",
        "time": "每週四3~4",
        "room": "公1F03",
        "credit": "2",
        "limit": 60,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "原「倫理學」更名。行政系學生選讀，不列入其通識畢業學分數。"
    },
    {
        "id": "U4274",
        "name": "二十世紀與全球化",
        "teacher": "張喬婷",
        "dim": "向度四",
        "time": "每週五5~6",
        "room": "社113",
        "credit": "2",
        "limit": 60,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "請協助安排社科院與U4286同一教室"
    },
    {
        "id": "U4277",
        "name": "Python資料科學與人工智慧",
        "teacher": "王孫崇",
        "dim": "向度五",
        "time": "每週五3~4",
        "room": "社105",
        "credit": "2",
        "limit": 60,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": "經濟系、智永學程學生修習不列入通識畢業學分。"
    },
    {
        "id": "U4278",
        "name": "公民暨道德教育",
        "teacher": "黃薏文",
        "dim": "向度二",
        "time": "每週三5~6",
        "room": "社203",
        "credit": "2",
        "limit": 50,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": ""
    },
    {
        "id": "U4280",
        "name": "族群與多元文化",
        "teacher": "張朝琴",
        "dim": "向度三",
        "time": "每週五7~8",
        "room": "電1F06",
        "credit": "2",
        "limit": 60,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": ""
    },
    {
        "id": "U4282",
        "name": "淺談地震",
        "teacher": "林炯明",
        "dim": "向度五",
        "time": "每週一1~2",
        "room": "電1F03",
        "credit": "2",
        "limit": 50,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "請安排電機資訊大樓教室"
    },
    {
        "id": "U4286",
        "name": "生物科技產業",
        "teacher": "張喬婷",
        "dim": "向度五",
        "time": "每週五7~8",
        "room": "社113",
        "credit": "2",
        "limit": 60,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "請協助安排社科院與U4274同一教室"
    },
    {
        "id": "U4290",
        "name": "中華民國憲法",
        "teacher": "詹靜芬",
        "dim": "向度三",
        "time": "每週五3~4",
        "room": "公1F27",
        "credit": "2",
        "limit": 105,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": "行政系、法律系學生修習不列入通識畢業學分。2月21日麻煩請改至公1F27上課。"
    },
    {
        "id": "U4292",
        "name": "創新與創業",
        "teacher": "葉斯偉",
        "dim": "向度四",
        "time": "每週三5~6",
        "room": "公1F11",
        "credit": "2",
        "limit": 60,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": ""
    },
    {
        "id": "U4303",
        "name": "日本劇場與大眾文化",
        "teacher": "李思漢",
        "dim": "向度六",
        "time": "每週二7~8",
        "room": "文2F08",
        "credit": "2",
        "limit": 50,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": ""
    },
    {
        "id": "U4306",
        "name": "視覺藝術",
        "teacher": "吳國淳",
        "dim": "向度一",
        "time": "每週二7~8",
        "room": "法2F13",
        "credit": "2",
        "limit": 50,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "希望安排在法學院教室+第二教室社科院203教室"
    },
    {
        "id": "U4313",
        "name": "人權、正義與公共議題",
        "teacher": "洪偉勝",
        "dim": "向度三",
        "time": "每週五7~8",
        "room": "公1F13",
        "credit": "2",
        "limit": 60,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "行政系學生修習不列入通識畢業學分"
    },
    {
        "id": "U4315",
        "name": "傳播與文化",
        "teacher": "雷碧秀",
        "dim": "向度三",
        "time": "每週一1~2",
        "room": "社114",
        "credit": "2",
        "limit": 50,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": ""
    },
    {
        "id": "U4324",
        "name": "氣候變遷與永續能源",
        "teacher": "陳思先",
        "dim": "向度五",
        "time": "每週四7~8",
        "room": "",
        "credit": "2",
        "limit": 40,
        "enrolled": 0,
        "can_add": "否",
        "lang": "英語 English",
        "note": "智永學程學生修習者，不列入其通識畢業學分。 ★全英語授課。 ★已修習開設於行政系之選修學分者，請勿重複修課；重複修課者不列入通識學分數。 永續發展與治理英語學士學分學程/微學程。"
    },
    {
        "id": "U4329",
        "name": "氣象與人生",
        "teacher": "林炯明",
        "dim": "向度五",
        "time": "每週一3~4",
        "room": "電1F03",
        "credit": "2",
        "limit": 50,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "請安排電機資訊大樓教室"
    },
    {
        "id": "U4335",
        "name": "新媒體之媒體識讀",
        "teacher": "雷碧秀",
        "dim": "向度三",
        "time": "每週一3~4",
        "room": "社114",
        "credit": "2",
        "limit": 50,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": ""
    },
    {
        "id": "U4337",
        "name": "租稅與生活",
        "teacher": "曾光文",
        "dim": "向度四",
        "time": "每週二7~8",
        "room": "公1F30",
        "credit": "2",
        "limit": 99,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "經濟系、財政系學生選讀，不列入其通識畢業學分數。"
    },
    {
        "id": "U4339",
        "name": "人工智慧導論",
        "teacher": "王孫崇",
        "dim": "向度五",
        "time": "每週三3~4",
        "room": "社103",
        "credit": "2",
        "limit": 60,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": "資工系、電機系、智永學程學生修習不列入通識畢業學分。"
    },
    {
        "id": "U4350",
        "name": "消費者保護法與現代社會",
        "teacher": "葉斯偉",
        "dim": "向度三",
        "time": "每週一5~6",
        "room": "公1F11",
        "credit": "2",
        "limit": 60,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "法律系、金融系學生選讀，不列入其通識畢業學分數。"
    },
    {
        "id": "U4351",
        "name": "科技與法律",
        "teacher": "葉斯偉",
        "dim": "向度三",
        "time": "每週一7~8",
        "room": "公1F11",
        "credit": "2",
        "limit": 60,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "法律系學生選讀，不列入其通識畢業學分數。"
    },
    {
        "id": "U4352",
        "name": "現代藝術與美學",
        "teacher": "吳國淳",
        "dim": "向度一",
        "time": "每週一5~6",
        "room": "法2F13",
        "credit": "2",
        "limit": 50,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "希望安排在法學院教室+第二教室社科院203教室"
    },
    {
        "id": "U4354",
        "name": "家庭與醫學",
        "teacher": "陳介然",
        "dim": "向度五",
        "time": "每週五3~4",
        "room": "法2F02",
        "credit": "2",
        "limit": 75,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": "加簽的同學，不用來信，請第一堂課，到教室登記。"
    },
    {
        "id": "U4358",
        "name": "臺法工藝文化探索",
        "teacher": "曾秀珍",
        "dim": "向度四",
        "time": "每週五7~8",
        "room": "社112",
        "credit": "2",
        "limit": 50,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": "請安排 社112。"
    },
    {
        "id": "U4360",
        "name": "職場災害與防治",
        "teacher": "張朝琴",
        "dim": "向度三",
        "time": "每週五5~6",
        "room": "電1F06",
        "credit": "2",
        "limit": 60,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": ""
    },
    {
        "id": "U4361",
        "name": "環境倫理學",
        "teacher": "林炯明",
        "dim": "向度二",
        "time": "每週一5~6",
        "room": "電1F03",
        "credit": "2",
        "limit": 50,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "請安排電機資訊大樓教室"
    },
    {
        "id": "U4369",
        "name": "海山地區的藝術與文化創意產業",
        "teacher": "楊凡逸",
        "dim": "向度一",
        "time": "每週二7~8",
        "room": "文4F08",
        "credit": "2",
        "limit": 40,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": ""
    },
    {
        "id": "U4375",
        "name": "臺灣音樂與文化",
        "teacher": "林子晴",
        "dim": "向度一",
        "time": "每週二3~4",
        "room": "社203",
        "credit": "2",
        "limit": 40,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": "請安排社203。"
    },
    {
        "id": "U4376",
        "name": "明清小說與社會",
        "teacher": "辛法春",
        "dim": "向度六",
        "time": "每週二3~4",
        "room": "文1F10",
        "credit": "2",
        "limit": 60,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "教室請排文2F01，謝謝。"
    },
    {
        "id": "U4387",
        "name": "大學生的必修學分—情感教育",
        "teacher": "******",
        "dim": "向度二",
        "time": "每週未維護0",
        "room": "資B1F-02",
        "credit": "2",
        "limit": 35,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "本課程為陽明交大跨校磨課師通識課程,使用ewant平台授課。授課教師:陳斐娟老師；限電腦加退選;不開放人工加退選。選課學生不需自行註冊平台，於加退選結束後由校方依選課名單統一造冊送ewant平台註冊。"
    },
    {
        "id": "U4527",
        "name": "衛生保健",
        "teacher": "******",
        "dim": "向度五",
        "time": "每週四5~6",
        "room": "資B1F-02",
        "credit": "2",
        "limit": 45,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "台灣大學遠距課程；時間四13:20~15:00；程劭儀老師；限電腦加退選;不開放人工加退選。"
    },
    {
        "id": "U4529",
        "name": "國際政治與國際關係",
        "teacher": "曾秀珍",
        "dim": "向度四",
        "time": "每週一1~2",
        "room": "社112",
        "credit": "2",
        "limit": 50,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": "行政系學生選讀，不列入其通識畢業學分數。請安排 社101。"
    },
    {
        "id": "U4627",
        "name": "近世中國的社會與文化",
        "teacher": "何淑宜",
        "dim": "向度六",
        "time": "每週四7~8",
        "room": "文2F10",
        "credit": "2",
        "limit": 40,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "教室請安排人文學院。歷史系學生選讀者不列入其通識畢業學分數。"
    },
    {
        "id": "U4628",
        "name": "口語表達與人際溝通",
        "teacher": "郭慧娟",
        "dim": "向度二",
        "time": "每週一7~8",
        "room": "文1F10",
        "credit": "2",
        "limit": 50,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "中文系學生選讀，不列入通識畢業學分數。"
    },
    {
        "id": "U4012",
        "name": "健康經濟與財務管理之人工智慧應用",
        "teacher": "楊庫巴",
        "dim": "向度五",
        "time": "每週二5~7",
        "room": "電2F07",
        "credit": "3",
        "limit": 40,
        "enrolled": 0,
        "can_add": "否",
        "lang": "英語 English",
        "note": "資工系學生選讀，不列入其通識畢業學分數。教室請安排於電資音律大樓207教室，謝謝。"
    },
    {
        "id": "U4033",
        "name": "Python生成式AI實作",
        "teacher": "楊喨智",
        "dim": "向度五",
        "time": "每週一5~7",
        "room": "資1F-09",
        "credit": "3",
        "limit": 60,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": "資工系學生選讀，不列入其通識畢業學分數"
    },
    {
        "id": "U4034",
        "name": "國族與帝國",
        "teacher": "羅國暉",
        "dim": "向度六",
        "time": "每週二6~8",
        "room": "文2F12",
        "credit": "3",
        "limit": 40,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "教室安排，第一順位文院202室 (或其他設有兩台投影機的教室)，或人文學院的二樓教室。"
    },
    {
        "id": "U4043",
        "name": "運動與數位健康",
        "teacher": "傅艾迪",
        "dim": "向度五",
        "time": "每週四2~4",
        "room": "社205",
        "credit": "3",
        "limit": 30,
        "enrolled": 0,
        "can_add": "否",
        "lang": "英語 English",
        "note": "教室請安排於社科大樓206教室，謝謝。"
    },
    {
        "id": "U4060",
        "name": "現代東亞",
        "teacher": "羅國暉",
        "dim": "向度六",
        "time": "每週四6~8",
        "room": "文2F01",
        "credit": "3",
        "limit": 40,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": "教室安排，第一順位文院202室 (或其他設有兩台投影機的教室)，或人文學院的二樓教室。"
    },
    {
        "id": "U4065",
        "name": "Python生成式AI實作",
        "teacher": "楊喨智",
        "dim": "向度五",
        "time": "每週四7~9",
        "room": "資B1F-04",
        "credit": "3",
        "limit": 60,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": "資工系學生選讀，不列入其通識畢業學分數"
    },
    {
        "id": "U4085",
        "name": "都市地理與地方創生",
        "teacher": "蔡怡玟",
        "dim": "向度四",
        "time": "每週五2~4",
        "room": "社203",
        "credit": "3",
        "limit": 60,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": "不動產城鄉系學生選讀，不列其通識畢業學分。亦不列入不動產城鄉系畢業學分。請安排社203"
    },
    {
        "id": "U4128",
        "name": "保育生物學",
        "teacher": "陳湘繁",
        "dim": "向度五",
        "time": "每週一5~7",
        "room": "公2F06",
        "credit": "3",
        "limit": 30,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "請安排教室\"公205或公206\"，上課需要有長型大桌子。本課程為和資源所並列課程。"
    },
    {
        "id": "U4299",
        "name": "綠木家具設計實務",
        "teacher": "趙南開",
        "dim": "向度一",
        "time": "每週一2~4",
        "room": "木101",
        "credit": "3",
        "limit": 24,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": "請安排木藝教室。本課程需自行操作木工機具，自費購買木料 。"
    },
    {
        "id": "U4344",
        "name": "綠設計與木作藝術",
        "teacher": "郭家宏",
        "dim": "向度一",
        "time": "每週四2~4",
        "room": "木101",
        "credit": "3",
        "limit": 24,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "課程於三峽校區木師基地教室上課。本課程不提供材料包或半成品，需自行操作木工機具，自費購買木料與耗材。機具操作安全考量，因此無提供人工加簽。"
    },
    {
        "id": "U4381",
        "name": "綠木家具設計實務",
        "teacher": "趙南開",
        "dim": "向度一",
        "time": "每週一6~8",
        "room": "木101",
        "credit": "3",
        "limit": 8,
        "enrolled": 0,
        "can_add": "是",
        "lang": "中文",
        "note": "請安排木藝教室。本課程需自行操作木工機具，自費購買木料 。"
    },
    {
        "id": "U4382",
        "name": "綠設計與木作藝術",
        "teacher": "郭家宏",
        "dim": "向度一",
        "time": "每週四5~7",
        "room": "木101",
        "credit": "3",
        "limit": 8,
        "enrolled": 0,
        "can_add": "否",
        "lang": "中文",
        "note": "課程於三峽校區木師基地教室上課。本課程不提供材料包或半成品，需自行操作木工機具，自費購買木料與耗材。機具操作安全考量，因此無提供人工加簽。"
    }
];